package kurento

// Code generated by kurento-go-generator. DO NOT EDIT.

type RTCCertificateStats struct {
	Fingerprint          string
	FingerprintAlgorithm string
	Base64Certificate    string
	IssuerCertificateId  string
}
