package kurento

// Code generated by kurento-go-generator. DO NOT EDIT.

type ElementConnectionData struct {
	Source            MediaElement
	Sink              MediaElement
	Type              MediaType
	SourceDescription string
	SinkDescription   string
}
